#! /usr/bin/env python

import roslib
import rospy
from mission_controller import TurtlebotServer

def clean_params():
    rospy.delete_param("/mission_controller/agents")
    return

if __name__ == '__main__':
    rospy.init_node('mission_controller')

    try:
        tb_ns = rospy.get_param('~agents')
    except:
        rospy.set_param('~agents', [""])
        tb_ns = [""]

    for tb in tb_ns:
	print("Starting: "+ tb)
        TurtlebotServer(ns=tb)

    print("mission controller ready!")

    rospy.spin()

    rospy.on_shutdown(clean_params)
